### ISSUE TITLE
games should be replayable

### ISSUE THREAD

**Issue by medovina** [minception/Evora#10]
Today, if I run a series of games using a command such as

```
azul_console MonteCarloAI GreedyAI 10
```

then after the series finishes running I have no way to go back and replay any of the individual games.

Instead, I think each game that is run should get its own random seed.  For example, game number 0 could have seed 0, game number 1 could have seed 1 and so on.  I could then rerun any game using that seed to understand why its outcome occurred.

(My ad_ai branch seeds games in this way, so you could presumably implement this by taking this change from that branch.)

**Comment by medovina** [comment]
I've realized that even in the ad_ai branch, games with MonteCarloAI are not replayable.  If I run "azul_console MonteCarloAI GreedyAI 3" twice, then I get different outcomes and scores on each run.

The problem is that MonteCarloAI uses its own random number generators which are not influenced by the game seed.

Instead, I think that each Azul game should have a single random number generator that is initialized using a seed specified in the game constructor.  All agents that participate in the game, such as MonteCarloAI or RandomAI, should generate all their random numbers using that generator.  Then any game will be replayable if you specify the same seed again.  In my opinion this is an essential feature for debugging agents and understanding their behavior.

**Comment by minception** [comment]
Added in the commit fa0400e
