### ISSUE TITLE
move evaluation functions out of utils.cpp

### ISSUE THREAD

**Issue by medovina** [minception/Evora#16]
I think utils.cpp doesn't seem like a great home for functions such as score_move and evaluate_player.  To me the name "utils" implies general-purpose utility functions (e.g. string manipulation).  By contrast, score_move, evaluate_player and related functions are related to move evaluation, and are an important part of your agents' behavior.  I'd suggest moving them to a source file with a name such as evaluate.cpp or score.cpp.

**Comment by minception** [comment]
fixed in 03d4acc
