### ISSUE TITLE
alpha-beta pruning does not improve performance

### ISSUE THREAD

**Issue by medovina** [minception/Evora#19]
(In running the tests below, I've built the code with a fix for #18 so that it is actually possible to specify options.)

I ran 5 games of MinimaxAI (at depth = 3) vs. GreedyAI:

```
$ build/ConsoleUI/azul_console MinimaxAI depth=3 GreedyAI 5
Player 2 : GreedyAI won game number 0
Score: 26:36
...
Player 2 : GreedyAI won game number 4
Score: 33:55
Elapsed time: 35.2843
Player MinimaxAI won 1 out of 5 games. Win rate: 20%
```

Then I ran the same, without alpha-beta pruning:

```
$ time build/ConsoleUI/azul_console MinimaxAI depth=3 abpruning=false GreedyAI 5
Player 2 : GreedyAI won game number 0
Score: 22:60
...
Player 2 : GreedyAI won game number 4
Score: 20:40
Elapsed time: 34.083
Player MinimaxAI won 0 out of 5 games. Win rate: 0%
```

Notice that the elapsed time _decreased_ slightly when I disabled alpha-beta pruning.  That seems wrong.  The code should run significantly faster when alpha-beta pruning is enabled.

**Comment by minception** [comment]
tested in 9d23594 now improves performance
