### ISSUE TITLE
Meson error: File ai.cpp.does not exist

### ISSUE THREAD

**Issue by medovina** [minception/Evora#9]
When I run Meson in the Evora master branch on Ubuntu, I get this error:

```
Engine/meson.build:3:0: ERROR: File ai.cpp does not exist.
```

The problem is that the repository contains files 'AI.cpp' and 'AI.h', but in meson.build the capitalization is 'ai.cpp'.  That may not matter on Windows, where filenames are case-insensitive, but on Unix 'AI.cpp' and 'ai.cpp' are distinct filenames.

**Comment by minception** [comment]
fixed
